[package]
name = "rimecraft"
version = "1.19.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4.1.14", features = ["derive"] }
fast-socks5 = "0.8.1"
favent = "0.1.0"
log = "0.4.17"
log4rs = "1.2.0"
once_cell = "1.17.1"
serde = { version = "1.0.159", features = ["serde_derive"] }
serde_json = "1.0.95"
tokio = "1.27.0"
uuid = { version = "1.3.0", features = ["v3", "v4"] }
datafixerupper = { version = "*", path = "../datafixerupper" }
md-5 = "0.10.5"
substring = "1.4.5"
