[package]
name = "rimecraft"
version = "1.19.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "*", features = ["serde"] }
clap = { version = "*", features = ["derive"] }
fast-socks5 = "*"
log = "*"
once_cell = "*"
serde = { version = "*", features = ["serde_derive"] }
serde_json = "*"
uuid = { version = "*", features = ["v3", "v4"] }
datafixerupper = { version = "*", path = "../datafixerupper" }
md-5 = "*"
substring = "*"
url = "*"
glium = "*"
sysinfo = "*"
bytes = "*"
glam = "*"
